#! /bin/bash


_piratebot_zip () {
    if [[ $PLUGINS_REPO ]]
    then
        echo "https://github.com/${PLUGINS_REPO}/archive/master.zip"
    else
        echo "https://github.com/The-HellBot/Plugins/archive/master.zip"
    fi
}

_starter () {
    echo "ಢಢ Downloading Pirate...."
    piratepath="Plugins.zip"

    wget -q $(_hellbot_zip) -O "$piratepath"
    PIRATEPATH=$(zipinfo -1 "$piratepath" | grep -v "/.");
    unzip -qq "$piratepath"
    rm -rf "$piratepath"
    cd $PIRATEPATH
    python3 ../updater.py ../requirements.txt requirements.txt

    echo "ಢಢ Starting Pirate...."
    chmod 777 start.sh
    ./start.sh
}

_starter
